version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: jobterview-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jobterview
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    container_name: jobterview-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]