spring:
  profiles:
    active: local
    group:
      local:
        - domain
        - security

  config:
    import: optional:classpath:env/env.properties

  cache:
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  swagger-ui:
    path: /docs
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: 1

logging:
  level:
    org.springframework.security: INFO
    org.springframework.cache.interceptor.CacheInterceptor: TRACE
    org.springframework.data.redis: DEBUG