spring:
  profiles:
    active: local
    group:
      local:
        - domain

  config:
    import: optional:classpath:env/env.properties

  batch:
    job:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 10000
          starttls:
            enable: true

---

spring:
  config:
    activate:
      on-profile: local
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
---